if(EXISTS "/home/superphenotype/.gitrepos/Modular/modular-tests-b12d07c_tests.cmake")
  include("/home/superphenotype/.gitrepos/Modular/modular-tests-b12d07c_tests.cmake")
else()
  add_test(modular-tests_NOT_BUILT-b12d07c modular-tests_NOT_BUILT-b12d07c)
endif()
